# Generated by Django 4.1.3 on 2022-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('FCB', 'Formatação com Backup'), ('FSB', 'Formatação sem Backup'), ('MDC', 'Montagem de Desktop Completa'), ('MNC', 'Montagem de Notebook Completa'), ('LC', 'Limpeza Completa')], max_length=150),
        ),
    ]
